package entity;
// Generated Nov 19, 2021 12:53:04 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer uid;
     private String user;
     private String pass;
     private Integer isSell;
     private Integer isAdmin;

    public Account() {
    }

    public Account(String user, String pass, Integer isSell, Integer isAdmin) {
       this.user = user;
       this.pass = pass;
       this.isSell = isSell;
       this.isAdmin = isAdmin;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Integer getIsSell() {
        return this.isSell;
    }
    
    public void setIsSell(Integer isSell) {
        this.isSell = isSell;
    }
    public Integer getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin;
    }




}


