package entity;
// Generated Nov 19, 2021 12:53:04 PM by Hibernate Tools 4.3.1



/**
 * Categorymen generated by hbm2java
 */
public class Categorymen  implements java.io.Serializable {


     private int cmid;
     private String cmname;
     private int cid;

    public Categorymen() {
    }

    public Categorymen(int cmid, String cmname, int cid) {
       this.cmid = cmid;
       this.cmname = cmname;
       this.cid = cid;
    }
   
    public int getCmid() {
        return this.cmid;
    }
    
    public void setCmid(int cmid) {
        this.cmid = cmid;
    }
    public String getCmname() {
        return this.cmname;
    }
    
    public void setCmname(String cmname) {
        this.cmname = cmname;
    }
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }




}


