package entity;
// Generated Nov 19, 2021 12:53:04 PM by Hibernate Tools 4.3.1



/**
 * Categorywomen generated by hbm2java
 */
public class Categorywomen  implements java.io.Serializable {


     private int cwid;
     private String cwname;
     private int cid;

    public Categorywomen() {
    }

    public Categorywomen(int cwid, String cwname, int cid) {
       this.cwid = cwid;
       this.cwname = cwname;
       this.cid = cid;
    }
   
    public int getCwid() {
        return this.cwid;
    }
    
    public void setCwid(int cwid) {
        this.cwid = cwid;
    }
    public String getCwname() {
        return this.cwname;
    }
    
    public void setCwname(String cwname) {
        this.cwname = cwname;
    }
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }




}


