package entity;
// Generated Nov 19, 2021 12:53:04 PM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int cid;
     private String cname;

    public Category() {
    }

    public Category(int cid, String cname) {
       this.cid = cid;
       this.cname = cname;
    }
   
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }




}


