package entity;
// Generated Nov 19, 2021 12:53:04 PM by Hibernate Tools 4.3.1



/**
 * Categoryfurnitures generated by hbm2java
 */
public class Categoryfurnitures  implements java.io.Serializable {


     private int cfid;
     private String cfname;
     private int cid;

    public Categoryfurnitures() {
    }

    public Categoryfurnitures(int cfid, String cfname, int cid) {
       this.cfid = cfid;
       this.cfname = cfname;
       this.cid = cid;
    }
   
    public int getCfid() {
        return this.cfid;
    }
    
    public void setCfid(int cfid) {
        this.cfid = cfid;
    }
    public String getCfname() {
        return this.cfname;
    }
    
    public void setCfname(String cfname) {
        this.cfname = cfname;
    }
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }




}


