package entity;
// Generated Nov 19, 2021 12:53:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Productcart generated by hbm2java
 */
public class Productcart  implements java.io.Serializable {


     private Integer idprocart;
     private Integer productId;
     private String pcname;
     private BigDecimal pcprice;
     private String cateDetailName;
     private Integer personId;
     private Integer ischeckout;

    public Productcart() {
    }

	
    public Productcart(String cateDetailName) {
        this.cateDetailName = cateDetailName;
    }
    public Productcart(Integer productId, String pcname, BigDecimal pcprice, String cateDetailName, Integer personId, Integer ischeckout) {
       this.productId = productId;
       this.pcname = pcname;
       this.pcprice = pcprice;
       this.cateDetailName = cateDetailName;
       this.personId = personId;
       this.ischeckout = ischeckout;
    }
   
    public Integer getIdprocart() {
        return this.idprocart;
    }
    
    public void setIdprocart(Integer idprocart) {
        this.idprocart = idprocart;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getPcname() {
        return this.pcname;
    }
    
    public void setPcname(String pcname) {
        this.pcname = pcname;
    }
    public BigDecimal getPcprice() {
        return this.pcprice;
    }
    
    public void setPcprice(BigDecimal pcprice) {
        this.pcprice = pcprice;
    }
    public String getCateDetailName() {
        return this.cateDetailName;
    }
    
    public void setCateDetailName(String cateDetailName) {
        this.cateDetailName = cateDetailName;
    }
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    public Integer getIscheckout() {
        return this.ischeckout;
    }
    
    public void setIscheckout(Integer ischeckout) {
        this.ischeckout = ischeckout;
    }




}


